"""R11 Champion Validation 的冻结契约、工件与决策原语。"""

from .contracts import (
    ABLATION_VARIANTS,
    BENCHMARK_IDS,
    CANDIDATE_SELECTION_ENABLED,
    CONSUMED_CONFIRMATION_INTERVAL,
    EXPERIMENT_ID,
    EXPERIMENT_TYPE,
    PROMOTION_ENABLED,
    RESEARCH_INTERVAL,
    SUBJECT_STATUS,
    SUBJECT_STRATEGY,
    TRIAL_COUNT,
    ConfirmationIntervalViolation,
    DateInterval,
    FrozenIdentity,
    StageResult,
    StageStatus,
    ValidationContract,
    ValidationLedger,
    append_ledger_entry,
    build_structured_artifact,
    canonical_hash,
    canonical_json,
    freeze_identity,
    validate_confirmation_interval,
)
from .decision import FinalAction, ValidationDecision, ValidationState, ValidationStateMachine, evaluate_final_decision
from .report import render_chinese_report, validate_structured_artifact

__all__ = [
    "ABLATION_VARIANTS",
    "BENCHMARK_IDS",
    "CANDIDATE_SELECTION_ENABLED",
    "CONSUMED_CONFIRMATION_INTERVAL",
    "EXPERIMENT_ID",
    "EXPERIMENT_TYPE",
    "PROMOTION_ENABLED",
    "RESEARCH_INTERVAL",
    "SUBJECT_STATUS",
    "SUBJECT_STRATEGY",
    "TRIAL_COUNT",
    "ConfirmationIntervalViolation",
    "DateInterval",
    "FinalAction",
    "FrozenIdentity",
    "StageResult",
    "StageStatus",
    "ValidationContract",
    "ValidationDecision",
    "ValidationLedger",
    "ValidationState",
    "ValidationStateMachine",
    "append_ledger_entry",
    "build_structured_artifact",
    "canonical_hash",
    "canonical_json",
    "evaluate_final_decision",
    "freeze_identity",
    "render_chinese_report",
    "validate_confirmation_interval",
    "validate_structured_artifact",
]
